version: '2'
volumes:
    sensor-data:
services:
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'sensor-data:/data'
  web:
    build: ./web
    privileged: true
    restart: always
    ports:
      - "80:80"
    depends_on:
      - influxdb
